BATCH_SIZE: 48
LAI: true
NUM_INSTANCES: 8
ROOT_DIR: ./dataset/VeRi/
alpha_ce: 0.6
backbone: ibn
beta_tri: 1.0
bias_lr_factor: 1
branch_layer: 3
circle_softmax: false
dataset: Veri776
epoch_freeze_L1toL3: 0
freeze_backbone_warmup: false
freeze_triplet_branches: 0
gallery_list_file: ./dataset/VeRi/name_test.txt
gamma: 0.1
gamma_ce: 0.4
gamma_t: 0.4
gn_init: kaiming
gpu: 0
group_norm: false
half_precision: false
hard_mining: true
label_smoothing: 0.1
linear_num: false
lr: 0.0001
margin_circle: 0.35
mean_losses: false
metric_loss: fastreidtriplet
metric_loss_trans: fastreidtriplet
milestones:
- 40
- 70
- 100
min_lr: 7.75e-05
model_arch: MBR_4B
momentum: 0.9
n_cams: 20
n_classes: 575
n_mean:
- 0.5
- 0.5
- 0.5
n_std:
- 0.5
- 0.5
- 0.5
n_views: 8
num_epochs: 120
num_workers_teste: 4
num_workers_train: 4
optimizer: Adam
p_hflip: 0.5
p_rerase: 0.5
parallel: false
pool: GAP
pool_trans: GAP
pool_tripletb: GAP
pretrain_gropnorm: false
pretrain_ongroups: true
query_dir: ./dataset/VeRi/image_query/
query_list_file: ./dataset/VeRi/name_query.txt
scale_circle: 64
sched_name: Warm_MultiStep
softmax_loss: torch_ce
test_keypoint: ./dataset/VeRi/keypoint_orient_test.txt
teste_dir: ./dataset/VeRi/image_test/
torch_seed: 0
train_dir: ./dataset/VeRi/image_train/
train_keypoint: ./dataset/VeRi/keypoint_orient_train.txt
train_list_file: ./dataset/VeRi/name_train.txt
triplet_margin: 0.1
triplet_margin_trans: 0.1
triplet_norm: false
validation_period: 10
warmup_factor: 0.0
warmup_iters: 10
warmup_method: linear
weight_decay: 0.0005
x_length: 256
y_length: 256
